config/routes.rb
Portfolio::Application.routes.draw do

  resources :projects do
    resources :images
  end

  resources :posts do
    resources :comments
  end
  
  resources :session, :about
  
  match "/login" => "session#new", :as => :login
  match "/logout" => "session#destroy", :as => :logout 
  match "/resume" => "about#resume", :as => :resume

  root :to => "projects#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project
  
  has_attached_file :photo, 
    :styles => { 
      :small => "150x150>",
      :medium => "200x200>"
    },
    :storage => :s3,
    :bucket => 'cml-portfolio',
    :s3_credentials => {
      :access_key_id => 'AKIAJHG7I3JMPXFW6F2A',
      :secret_access_key => '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'
    }
end

app/models/post.rb
class Post < ActiveRecord::Base    
  validates :name, :presence => true
  validates :title, :presence => true,
                    :length => { :minimum => 5 }
                    
  has_many :comments, :dependent => :destroy
  
  has_attached_file :photo, 
    :styles => { :small => "150x150>" },
    :storage => :s3,
    :bucket => 'cml-portfolio',
    :s3_credentials => {
      :access_key_id => 'AKIAJHG7I3JMPXFW6F2A',
      :secret_access_key => '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'
    }
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :images, :dependent => :destroy
  
  has_attached_file :thumbnail, 
    :styles => { :thumb => "50x50>" },
    :storage => :s3,
    :bucket => 'cml-portfolio',
    :s3_credentials => {
      :access_key_id => 'AKIAJHG7I3JMPXFW6F2A',
      :secret_access_key => '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'
    }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def resume
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :admin?
  
  private
  
  def authorize
    unless admin?
      flash[:notice] = "Unauthorized access"
      redirect_to root_path
      false
    end
  end
  
  def admin?
    session[:password] == "generalpw"
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate, :only => :destroy
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def create
    @project = Project.find(params[:project_id])
    @image = @project.images.create(params[:image])
    redirect_to project_path(@project)
  end
  
  def destroy
    @project = Project.find(params[:project_id])
    @image = @project.images.find(params[:id])
    @image.destroy
    redirect_to project_path(@project)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all(:order => "ranking")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
  end
  
  def create
    session[:password] = params[:password]
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def rank_projects
    projects = Project.all(:order => "ranking")
    return projects
  end
  
  def next_project_path
    # return array of ranked projects
    projects = rank_projects
    # return the position of project in ranked array
    proj_rank = rank_projects.index(@project)
    
    if @project == projects.last
      proj_rank = 0
    else
      proj_rank += 1
    end
    
    # returns id of the next project
    proj_id = projects[proj_rank].id
    return "/projects/#{proj_id}"
  end
  
  def prev_project_path
    # return array of ranked projects
    projects = rank_projects
    # return the position of project in ranked array
    proj_rank = rank_projects.index(@project)
    
    if @project == projects.first
      proj_rank = projects.size 
      proj_rank -= 1
    else
      proj_rank -= 1
    end
    
    # returns id of the next project
    proj_id = projects[proj_rank].id
    return "/projects/#{proj_id}"
  end
  
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/about/resume.html.haml
= image_tag "/images/landry-resume.jpg", :class => "resume"

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>

<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.post, comment],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br ?>
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_form.html.haml
.image_upload
  %b Add an image:

  = form_for([@project, @project.images.build], :html => {:multipart => true} ) do |f|
    .field
      = f.label :caption
      = f.text_field :caption
    .field
      = f.label :description
      = f.text_field :description
    .field
      = f.file_field :photo
    .actions
      = f.submit

app/views/images/_image.html.haml
.admin_image
  = image_tag image.photo.url(:small)
  %p 
    Caption:
    = image.caption
    %br Description:
    =image.description  
    = link_to 'Delete Image', [image.project, image], :confirm => 'Are you sure?', :method => :delete

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
  %title Portfolio
  = stylesheet_link_tag "scaffold", "app"
  = javascript_include_tag :defaults
  = csrf_meta_tag
  %link{ :href => "/images/favicon.ico", :rel => "shortcut icon", :type => "image/ico" }
  
%body
  .background
    #header
      = link_to "christina landry", root_path, { :class => "header_links", :id => "first" }
      = link_to "Resume", resume_path, { :class => "header_links" }
      = link_to "Contact", "mailto:cmlandry7@gmail.com", { :class => "header_links" }
      %a{ :href => "http://www.facebook.com/christina.landry", :target => "_blank" }
        %img.soc-buttons{ :src => "/images/fb-favicon.png" }
      %a{ :href => "http://www.linkedin.com/in/christinalandry", :target => "_blank" }
        %img.soc-buttons{ :src => "/images/linkedin-favicon.png" }

    = yield

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <%= image_tag @post.photo.url(:small) %>
</p>

<%= render :partial => "comments/comment",
            :collection => @post.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/projects/_form.html.haml
= form_for @project, :html => {:multipart => true} do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :date
    = f.text_field :date
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :synopsis, "Description Part 2"
    = f.text_area :synopsis
  .field
    = f.label :ranking
    = f.text_field :ranking
  .field
    = f.label :thumbnail
    = f.file_field :thumbnail
  .actions
    = f.submit 'Save'

app/views/projects/_navigation.html.haml
.project_nav
  - Project.all.each do |project|
    .nav_thumb
      - thumb_url = project.thumbnail.url(:thumb)
      = link_to (image_tag(thumb_url)), project

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
#projects
  - @projects.each do |project|
    - if project.thumbnail
      = link_to (image_tag(project.thumbnail.url, :class => "lrg_thumb")), project

- if admin?    
  .clearboth
  = link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

.project_div
  .project_images
    - @project.images.each do |image|
      .image_div
        = image_tag image.photo.url, :class => "proj_image"
        - if image.caption?
          .caption_div
            .image_caption= image.caption
  .project_info
    .pr_description
      .pr_thumb
        = image_tag @project.thumbnail.url(:thumb)
      .title_div
        .pr_title
          = @project.title
        = link_to ( image_tag("/images/back.png", :class => "nav_arrow")), prev_project_path
        = link_to ( image_tag("/images/up.png", :class => "nav_arrow")), projects_path
        = link_to ( image_tag("/images/next.png", :class => "nav_arrow")), next_project_path
        .pr_date=@project.date
      .clearboth
      = @project.description
      %p=@project.synopsis

.clearboth
- if admin?
  = link_to 'Edit', edit_project_path(@project)
  \|
  = link_to 'Back', projects_path
  \|
  = link_to 'Destroy', @project, :confirm => 'Are you sure?', :method => :delete
  \|
  Ranking #{@project.ranking}
  #admin-images
    = render :partial => "images/image", :collection => @project.images
  #image-form
    = render "images/form"

app/views/session/destroy.html.haml
%h1 Session#destroy
%p Find me in app/views/session/destroy.html.haml

app/views/session/new.html.haml
Login Page

= form_tag "session" do
  = text_field_tag :password
  